local({
    r <- getOption("repos")
    r["CRAN"] <- "https://cran-r.c3sl.ufpr.br/"
    options(repos = r)
})
install.packages("devtools")
install.packages("aws.s3")
install.packages("shinythemes")
install.packages("shinycssloaders")
install.packages("shinydashboard")
install.packages("plotly")
install.packages("leaflet")
install.packages("ggthemes")
install.packages('gdalcubes')
install.packages("ggmap")
install.packages("ggplot2")
install.packages("ggrepel")
install.packages("ggsom")
install.packages("ggsom")
install.packages("ggpubr")
install.packages("ggpubr")
install.packages("tidyverse")
install.packages("geojsonio")
install.packages("collapsibleTree")
install.packages("dendextend")
install.packages("caret")
install.packages("keras")
install.packages("moments")
install.packages("rstac")
install.packages("randomForest")
install.packages("fitdistrplus")
install.packages("rpart", dependencies = TRUE)
install.packages("rpart.plot", dependencies = TRUE)
install.packages("sf", dependencies = TRUE)
remotes::install_github("e-sensing/sits")
remotes::install_github("e-sensing/sitsdata")
remotes::install_github("e-sensing/Rwtss")
